.LINECONT +
.DEFINE CreditsTextAddrs \
    CreditsTextLines+0, \
    CreditsTextLines+9, \
    CreditsTextLines+20, \
    CreditsTextLines+44, \
    CreditsTextLines+68, \
    CreditsTextLines+92, \
    CreditsTextLines+108, \
    CreditsTextLines+132, \
    CreditsTextLines+156, \
    CreditsTextLines+170, \
    CreditsTextLines+184, \
    CreditsTextLines+191, \
    CreditsTextLines+215, \
    CreditsTextLines+241, \
    CreditsTextLines+253, \
    CreditsTextLines+278, \
    CreditsTextLines+294, \
    CreditsTextLines+310, \
    CreditsTextLines+325, \
    CreditsTextLines+346, \
    CreditsTextLines+365, \
    CreditsTextLines+373, \
    CreditsTextLines+398
.LINECONT -
